[[redirects]]
  from = "/osu/skins"
  to = "/osu/skins/index.html"
  status = 200

[[redirects]]
  from = "/osu"
  to = "/osu/skins/index.html"
  status = 200

[[redirects]]
  from = "/osu/tools"
  to = "/osu/skins/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
